version: "3"

# Containers we are going to run
services:
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define the volumes
volumes:
  pgdata:
